language: python
python:
- '3.6'
install:
- pip install ansible>=2.4 molecule>=2.6 testinfra>=1.10 apache-libcloud requests
  google-auth pycrypto
env:
  matrix:
  - GCE_CREDENTIALS_FILE="$(pwd)/credentials.json"
  global:
  - secure: sXBudxBELFdzxCzwyfJ0PvHI2Rofm6Y96dZXpYAoEiZnxcJcc0tlbpQbW/gW+uuw7bopN29KN8um7Y2FJqHwgrRuBGehM3gHRlvPYC8sav9fK9C6mS9hNFXjTct7MmpFyqjX5KSS3RPfpgOtazZeFHE6aabwguZQFq/h81EhcXTRYhFdHvnXMTKHRcE6vEIuoATMBrX0pWXDWF3xmpceFTeR7AERB7NBKcpAWzVCQ7sJgHQU8V3MPG/h5dOTetuOcu+rpNniwb1L5I81aD6EVN09pnk7xuZXfuEQa9ErGNozDFa65JWae3zTCE7mAdThPiuoYrsMnRGiWVg71ZfY0DaJLqEVU+reTpS9YpRURSTzZOwOg8xjDLF5n3s5nieMzD41S8CkTmgdoaDSb46QzOm4sT076zaHkEjXtcIOWHoX+zg6QXW2UkjYFErqC3+fV1jpsCXjtMIlIlEu3IxoG/3qgiir8YiMKCp//AP4TPsHdANgsSrQ3RX7/YonB2STCOvpU5O6JyZSEh3yH6cH7+QVceO+Hlio57KlnolNSLIhivb+d5BlJZRtC/9j3TpjZipmDt2rb6yi5OOPyBQP136b8ssvmvV3bEPVEuKQv/i0gysc7wNx2TXIjq05VfDtgFGFDcnJZw3wh+81J18ZPQuMLQD/QMkYOSeAOxHkBjg=
  - secure: G/kPsQ//OOzLTEZ83fgBAK/AWIQy/PAqOPoEwjgzAir2Rr1NVvMB7/KN14p+tkHN3GkV/V4ctfYFKI2LWCHtowlaCnAUV0pFaPksygszPcWJkwvNF4KWFu5VxyODaGlUN9nxYEw5Rq5NDI7jZz/G5bKmS7vgccbMmMcUel0672Jr6GcUhBIDJhNGJHKmgYojOrn/lOmT5Qt7SRvXsooLiemZkoyNlaeVAZkXhflZYVDRE6XL1m1uN6ifNysy5fF0J6aAGFF3C6xS9LMgQeup4Tsk1R0ilx8GWL3EuxoMCVQT48l4Rt+x7Or306d8DBI1EL7Jwfz2glVUnGP3Xj7COdOzsdctHTNLONWxn7b+Rhq9UJaODJ1tqQ+OGa5fJ6u47FHnDWH+JN3lEKG6bfW/iQpFdI7SHtGzdpbw7rJknEwgWcf7WuNbaLGk5V4lO8SRR5qeNWlJacpSlo8kVDRt5bm7PT6/UoFS2kMmOKTz9GbqtXnwt2mEbEexp+Ap2NHQlINNkDyskUIANVc+hmAZWe+92I0onVuXFMWbPjlvvn/tZ/NhfdvkZIB0udUhsLhEvG0nHFtViSabEo0UU+Il365p/gc+SEzWHnZobPx073HR4yLi/+ZcGiFpE4BPAHCw2FnQErmWKO/mF4LJrbpdpRbwXzpHrtDnYtwdKJCHaoM=
  - secure: jggBCkNkBUaj2EB/dw8bvMtDVGZfRPPIXkZN3VIAzAmNcTZUcPlfqcFR7LNEfeVX28/p2LcIk/l8ciGhK6uTVkD5DOKmwDcCxU/GkCDVU8oLbh+kcchIX9h4Wvu1kQzSemaXQ6+7YsuDDrp111OGoJ6tgjWhxPJZ15aHVRMu3rRqyGapJvRuE3zS1q/5TkMVoY/NC8OOfm2dFl25IVtuwUiMPnFomqrN674dMyI7SXuz0o88WxW9NONTQYApZ6XWi38eWU3l4ftnztnr4Bw0gySBg+B6B/v5mOzk0rxWUwC8yJAAXmPFWHMnv4T4b03cU5MCj8Lm2UhvR6VE3umz8bxJVahSj42vFiHu6Hrv1LX0mhxRwSqPTIISmVd7c3D2v10xkkjHhdFQwl+5caOYSzf4PvvttZukawZT4JbbJ/XKxeUFzSixUvM8ppKoiEI+EHhrZj0mgfCfJOJNYRvFyxpx4D6X262TcJfXM2Iz7RPDYzpnc3LlX+roFmLVdVo/4nJFMJETm7+Ms5+mcNRQnZdXZ18Z6b4+jOIuUJG2jzR79dPyTlBisAZzGJFA72C1FbaHSAoxK4aBnbmO80SoJrs2SyhXPGFY9UIUIT6Iof0igttHUQ8Gl1A9XO1ibpcbRwmg7HYKt9Hj4IaaZRF6Ukr51V7FxzHKW6k7qsQSFk8=
script:
- molecule create
- molecule converge
- molecule verify
after_script:
- molecule destroy
before_install:
- openssl aes-256-cbc -K $encrypted_2db64f925e5c_key -iv $encrypted_2db64f925e5c_iv -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- mv google_compute_engine /home/travis/.ssh/
- chmod 0600 /home/travis/.ssh/google_compute_engine
notifications:
  slack:
    rooms:
      secure: 4sOCWwyTyuY+v16FTf/wqymQTv/5Gt0OACRxuUn3h26ug6P4r9jBwDF1pO4Ymp4HFaWFszE4eCy8DxuqEgRQdL3y6DkGiFKanTRzYfcubvTZxG7RfmrQweFeUGPPv4QEjOxYPCXAqoqPE7dFTjAWcs6gxx+Q3XzOkHRU6bpY1RniwcJzuwSU9+8IZ+N8AaD9FZoGfWoq84cbpS+vSLfJiMOIOx9vj4fmVaOTZ3uhGrtXBFYQKT2pMfhHMPUjiamprNn4xLUMrga6rL5EGuHhg5PUv5U0xaFCqMT/7I442qXz9n2Fej6mTDOnoDbUq43nrqTRYcjDv168Jznb7AjKLK8O6z0sfKiL5L9D8h1jKBNHeVxmpg0Yk/gE5zS75VfN8kq918hv9t7ZLiYs4/Hip1Jnf0Inqy8/i61tazw+/oseMbP7dRkZHYaBQNRexKs31OjrYZoufIySI0ePM8D7sprJJjXzpaEwq380DNQhZyV+Y53cZOrkoxvJ1/Xvu6QB0BQqvxVYCqy6ScYLfJHjUKNDQyNV5P2vrEea21RLo1bnhmxLvgrF/vEnmJSe6nXnt/TQcBh4KbaZ4F7BcH7TW8caRSUldQr5Z+MXzzGQV5dYkVMR6qXzAV6IQujQkeCoopl4BkzsCBLOlge79guIRCm5snpmQk10xkRPHwgxAaU=
